name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      multiple: true
      options:
        - CLI
        - VSCode Extension
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or logs if available.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - CLI version:
        - VSCode Extension version:
        - macOS version:
        - Xcode version:
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, logs, or any other relevant information.
    validations:
      required: false
