// Schema definition for the axe CLI ↔ VS Code Extension protocol.
// This file serves as the single source of truth for the protocol.
// The wire format is JSON Lines (one JSON object per line).
// protoc generates Go and TypeScript types from this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: preview.proto

package previewproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command is sent from the extension to the CLI via stdin.
// stream_id identifies the target stream (UUID v4, generated by extension).
type Command struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_AddStream
	//	*Command_RemoveStream
	//	*Command_SwitchFile
	//	*Command_NextPreview
	//	*Command_Input
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_preview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetAddStream() *AddStream {
	if x != nil {
		if x, ok := x.Payload.(*Command_AddStream); ok {
			return x.AddStream
		}
	}
	return nil
}

func (x *Command) GetRemoveStream() *RemoveStream {
	if x != nil {
		if x, ok := x.Payload.(*Command_RemoveStream); ok {
			return x.RemoveStream
		}
	}
	return nil
}

func (x *Command) GetSwitchFile() *SwitchFile {
	if x != nil {
		if x, ok := x.Payload.(*Command_SwitchFile); ok {
			return x.SwitchFile
		}
	}
	return nil
}

func (x *Command) GetNextPreview() *NextPreview {
	if x != nil {
		if x, ok := x.Payload.(*Command_NextPreview); ok {
			return x.NextPreview
		}
	}
	return nil
}

func (x *Command) GetInput() *Input {
	if x != nil {
		if x, ok := x.Payload.(*Command_Input); ok {
			return x.Input
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_AddStream struct {
	AddStream *AddStream `protobuf:"bytes,2,opt,name=add_stream,json=addStream,proto3,oneof"`
}

type Command_RemoveStream struct {
	RemoveStream *RemoveStream `protobuf:"bytes,3,opt,name=remove_stream,json=removeStream,proto3,oneof"`
}

type Command_SwitchFile struct {
	SwitchFile *SwitchFile `protobuf:"bytes,4,opt,name=switch_file,json=switchFile,proto3,oneof"`
}

type Command_NextPreview struct {
	NextPreview *NextPreview `protobuf:"bytes,5,opt,name=next_preview,json=nextPreview,proto3,oneof"`
}

type Command_Input struct {
	Input *Input `protobuf:"bytes,6,opt,name=input,proto3,oneof"`
}

func (*Command_AddStream) isCommand_Payload() {}

func (*Command_RemoveStream) isCommand_Payload() {}

func (*Command_SwitchFile) isCommand_Payload() {}

func (*Command_NextPreview) isCommand_Payload() {}

func (*Command_Input) isCommand_Payload() {}

// AddStream creates a new preview stream.
// The CLI allocates a simulator from the device pool based on device_type + runtime.
type AddStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`                               // Swift file path to preview
	DeviceType    string                 `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // e.g. "com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro"
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`                         // e.g. "com.apple.CoreSimulator.SimRuntime.iOS-18-2"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStream) Reset() {
	*x = AddStream{}
	mi := &file_preview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStream) ProtoMessage() {}

func (x *AddStream) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStream.ProtoReflect.Descriptor instead.
func (*AddStream) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{1}
}

func (x *AddStream) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *AddStream) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *AddStream) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// RemoveStream stops and removes a preview stream.
type RemoveStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStream) Reset() {
	*x = RemoveStream{}
	mi := &file_preview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStream) ProtoMessage() {}

func (x *RemoveStream) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStream.ProtoReflect.Descriptor instead.
func (*RemoveStream) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{2}
}

// SwitchFile changes the previewed file within an existing stream (hot-reload).
type SwitchFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchFile) Reset() {
	*x = SwitchFile{}
	mi := &file_preview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchFile) ProtoMessage() {}

func (x *SwitchFile) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchFile.ProtoReflect.Descriptor instead.
func (*SwitchFile) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{3}
}

func (x *SwitchFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// NextPreview cycles to the next #Preview block in the current file.
type NextPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextPreview) Reset() {
	*x = NextPreview{}
	mi := &file_preview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextPreview) ProtoMessage() {}

func (x *NextPreview) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextPreview.ProtoReflect.Descriptor instead.
func (*NextPreview) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{4}
}

// Input forwards user interaction (touch/text) to the simulator.
type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Input_TouchDown
	//	*Input_TouchMove
	//	*Input_TouchUp
	//	*Input_Text
	Event         isInput_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_preview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{5}
}

func (x *Input) GetEvent() isInput_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Input) GetTouchDown() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*Input_TouchDown); ok {
			return x.TouchDown
		}
	}
	return nil
}

func (x *Input) GetTouchMove() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*Input_TouchMove); ok {
			return x.TouchMove
		}
	}
	return nil
}

func (x *Input) GetTouchUp() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*Input_TouchUp); ok {
			return x.TouchUp
		}
	}
	return nil
}

func (x *Input) GetText() *TextEvent {
	if x != nil {
		if x, ok := x.Event.(*Input_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isInput_Event interface {
	isInput_Event()
}

type Input_TouchDown struct {
	TouchDown *TouchEvent `protobuf:"bytes,1,opt,name=touch_down,json=touchDown,proto3,oneof"`
}

type Input_TouchMove struct {
	TouchMove *TouchEvent `protobuf:"bytes,2,opt,name=touch_move,json=touchMove,proto3,oneof"`
}

type Input_TouchUp struct {
	TouchUp *TouchEvent `protobuf:"bytes,3,opt,name=touch_up,json=touchUp,proto3,oneof"`
}

type Input_Text struct {
	Text *TextEvent `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

func (*Input_TouchDown) isInput_Event() {}

func (*Input_TouchMove) isInput_Event() {}

func (*Input_TouchUp) isInput_Event() {}

func (*Input_Text) isInput_Event() {}

type TouchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"` // 0.0–1.0 (left to right)
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"` // 0.0–1.0 (top to bottom)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	mi := &file_preview_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{6}
}

func (x *TouchEvent) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TouchEvent) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type TextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // single character
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEvent) Reset() {
	*x = TextEvent{}
	mi := &file_preview_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEvent) ProtoMessage() {}

func (x *TextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEvent.ProtoReflect.Descriptor instead.
func (*TextEvent) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{7}
}

func (x *TextEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Event is sent from the CLI to the extension via stdout.
// stream_id identifies which stream this event belongs to.
type Event struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Frame
	//	*Event_StreamStarted
	//	*Event_StreamStopped
	//	*Event_StreamStatus
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_preview_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetFrame() *Frame {
	if x != nil {
		if x, ok := x.Payload.(*Event_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *Event) GetStreamStarted() *StreamStarted {
	if x != nil {
		if x, ok := x.Payload.(*Event_StreamStarted); ok {
			return x.StreamStarted
		}
	}
	return nil
}

func (x *Event) GetStreamStopped() *StreamStopped {
	if x != nil {
		if x, ok := x.Payload.(*Event_StreamStopped); ok {
			return x.StreamStopped
		}
	}
	return nil
}

func (x *Event) GetStreamStatus() *StreamStatus {
	if x != nil {
		if x, ok := x.Payload.(*Event_StreamStatus); ok {
			return x.StreamStatus
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Frame struct {
	Frame *Frame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

type Event_StreamStarted struct {
	StreamStarted *StreamStarted `protobuf:"bytes,3,opt,name=stream_started,json=streamStarted,proto3,oneof"`
}

type Event_StreamStopped struct {
	StreamStopped *StreamStopped `protobuf:"bytes,4,opt,name=stream_stopped,json=streamStopped,proto3,oneof"`
}

type Event_StreamStatus struct {
	StreamStatus *StreamStatus `protobuf:"bytes,5,opt,name=stream_status,json=streamStatus,proto3,oneof"`
}

func (*Event_Frame) isEvent_Payload() {}

func (*Event_StreamStarted) isEvent_Payload() {}

func (*Event_StreamStopped) isEvent_Payload() {}

func (*Event_StreamStatus) isEvent_Payload() {}

// Frame contains a base64-encoded JPEG preview image.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"` // device name, e.g. "iPhone 16 Pro"
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`     // previewed file path
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`     // base64-encoded JPEG
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_preview_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{9}
}

func (x *Frame) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Frame) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Frame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// StreamStarted is sent when an AddStream completes successfully.
type StreamStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreviewCount  int32                  `protobuf:"varint,1,opt,name=preview_count,json=previewCount,proto3" json:"preview_count,omitempty"` // number of #Preview blocks in the file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStarted) Reset() {
	*x = StreamStarted{}
	mi := &file_preview_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStarted) ProtoMessage() {}

func (x *StreamStarted) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStarted.ProtoReflect.Descriptor instead.
func (*StreamStarted) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{10}
}

func (x *StreamStarted) GetPreviewCount() int32 {
	if x != nil {
		return x.PreviewCount
	}
	return 0
}

// StreamStopped is sent when a stream ends (error or user action).
type StreamStopped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`         // e.g. "build_error", "runtime_error", "removed"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`       // human-readable detail
	Diagnostic    string                 `protobuf:"bytes,3,opt,name=diagnostic,proto3" json:"diagnostic,omitempty"` // compiler output excerpt for build errors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStopped) Reset() {
	*x = StreamStopped{}
	mi := &file_preview_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStopped) ProtoMessage() {}

func (x *StreamStopped) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStopped.ProtoReflect.Descriptor instead.
func (*StreamStopped) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{11}
}

func (x *StreamStopped) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StreamStopped) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamStopped) GetDiagnostic() string {
	if x != nil {
		return x.Diagnostic
	}
	return ""
}

// StreamStatus reports progress during stream initialization.
type StreamStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"` // "booting", "building", "installing", "running"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatus) Reset() {
	*x = StreamStatus{}
	mi := &file_preview_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatus) ProtoMessage() {}

func (x *StreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatus.ProtoReflect.Descriptor instead.
func (*StreamStatus) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{12}
}

func (x *StreamStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

var File_preview_proto protoreflect.FileDescriptor

const file_preview_proto_rawDesc = "" +
	"\n" +
	"\rpreview.proto\x12\vaxe.preview\"\xd3\x02\n" +
	"\aCommand\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x127\n" +
	"\n" +
	"add_stream\x18\x02 \x01(\v2\x16.axe.preview.AddStreamH\x00R\taddStream\x12@\n" +
	"\rremove_stream\x18\x03 \x01(\v2\x19.axe.preview.RemoveStreamH\x00R\fremoveStream\x12:\n" +
	"\vswitch_file\x18\x04 \x01(\v2\x17.axe.preview.SwitchFileH\x00R\n" +
	"switchFile\x12=\n" +
	"\fnext_preview\x18\x05 \x01(\v2\x18.axe.preview.NextPreviewH\x00R\vnextPreview\x12*\n" +
	"\x05input\x18\x06 \x01(\v2\x12.axe.preview.InputH\x00R\x05inputB\t\n" +
	"\apayload\"Z\n" +
	"\tAddStream\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\"\x0e\n" +
	"\fRemoveStream\" \n" +
	"\n" +
	"SwitchFile\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\"\r\n" +
	"\vNextPreview\"\xe8\x01\n" +
	"\x05Input\x128\n" +
	"\n" +
	"touch_down\x18\x01 \x01(\v2\x17.axe.preview.TouchEventH\x00R\ttouchDown\x128\n" +
	"\n" +
	"touch_move\x18\x02 \x01(\v2\x17.axe.preview.TouchEventH\x00R\ttouchMove\x124\n" +
	"\btouch_up\x18\x03 \x01(\v2\x17.axe.preview.TouchEventH\x00R\atouchUp\x12,\n" +
	"\x04text\x18\x04 \x01(\v2\x16.axe.preview.TextEventH\x00R\x04textB\a\n" +
	"\x05event\"(\n" +
	"\n" +
	"TouchEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"!\n" +
	"\tTextEvent\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xa7\x02\n" +
	"\x05Event\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12*\n" +
	"\x05frame\x18\x02 \x01(\v2\x12.axe.preview.FrameH\x00R\x05frame\x12C\n" +
	"\x0estream_started\x18\x03 \x01(\v2\x1a.axe.preview.StreamStartedH\x00R\rstreamStarted\x12C\n" +
	"\x0estream_stopped\x18\x04 \x01(\v2\x1a.axe.preview.StreamStoppedH\x00R\rstreamStopped\x12@\n" +
	"\rstream_status\x18\x05 \x01(\v2\x19.axe.preview.StreamStatusH\x00R\fstreamStatusB\t\n" +
	"\apayload\"G\n" +
	"\x05Frame\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"4\n" +
	"\rStreamStarted\x12#\n" +
	"\rpreview_count\x18\x01 \x01(\x05R\fpreviewCount\"a\n" +
	"\rStreamStopped\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"diagnostic\x18\x03 \x01(\tR\n" +
	"diagnostic\"$\n" +
	"\fStreamStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phaseB6Z4github.com/k-kohey/axe/internal/preview/previewprotob\x06proto3"

var (
	file_preview_proto_rawDescOnce sync.Once
	file_preview_proto_rawDescData []byte
)

func file_preview_proto_rawDescGZIP() []byte {
	file_preview_proto_rawDescOnce.Do(func() {
		file_preview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preview_proto_rawDesc), len(file_preview_proto_rawDesc)))
	})
	return file_preview_proto_rawDescData
}

var file_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_preview_proto_goTypes = []any{
	(*Command)(nil),       // 0: axe.preview.Command
	(*AddStream)(nil),     // 1: axe.preview.AddStream
	(*RemoveStream)(nil),  // 2: axe.preview.RemoveStream
	(*SwitchFile)(nil),    // 3: axe.preview.SwitchFile
	(*NextPreview)(nil),   // 4: axe.preview.NextPreview
	(*Input)(nil),         // 5: axe.preview.Input
	(*TouchEvent)(nil),    // 6: axe.preview.TouchEvent
	(*TextEvent)(nil),     // 7: axe.preview.TextEvent
	(*Event)(nil),         // 8: axe.preview.Event
	(*Frame)(nil),         // 9: axe.preview.Frame
	(*StreamStarted)(nil), // 10: axe.preview.StreamStarted
	(*StreamStopped)(nil), // 11: axe.preview.StreamStopped
	(*StreamStatus)(nil),  // 12: axe.preview.StreamStatus
}
var file_preview_proto_depIdxs = []int32{
	1,  // 0: axe.preview.Command.add_stream:type_name -> axe.preview.AddStream
	2,  // 1: axe.preview.Command.remove_stream:type_name -> axe.preview.RemoveStream
	3,  // 2: axe.preview.Command.switch_file:type_name -> axe.preview.SwitchFile
	4,  // 3: axe.preview.Command.next_preview:type_name -> axe.preview.NextPreview
	5,  // 4: axe.preview.Command.input:type_name -> axe.preview.Input
	6,  // 5: axe.preview.Input.touch_down:type_name -> axe.preview.TouchEvent
	6,  // 6: axe.preview.Input.touch_move:type_name -> axe.preview.TouchEvent
	6,  // 7: axe.preview.Input.touch_up:type_name -> axe.preview.TouchEvent
	7,  // 8: axe.preview.Input.text:type_name -> axe.preview.TextEvent
	9,  // 9: axe.preview.Event.frame:type_name -> axe.preview.Frame
	10, // 10: axe.preview.Event.stream_started:type_name -> axe.preview.StreamStarted
	11, // 11: axe.preview.Event.stream_stopped:type_name -> axe.preview.StreamStopped
	12, // 12: axe.preview.Event.stream_status:type_name -> axe.preview.StreamStatus
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_preview_proto_init() }
func file_preview_proto_init() {
	if File_preview_proto != nil {
		return
	}
	file_preview_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_AddStream)(nil),
		(*Command_RemoveStream)(nil),
		(*Command_SwitchFile)(nil),
		(*Command_NextPreview)(nil),
		(*Command_Input)(nil),
	}
	file_preview_proto_msgTypes[5].OneofWrappers = []any{
		(*Input_TouchDown)(nil),
		(*Input_TouchMove)(nil),
		(*Input_TouchUp)(nil),
		(*Input_Text)(nil),
	}
	file_preview_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_Frame)(nil),
		(*Event_StreamStarted)(nil),
		(*Event_StreamStopped)(nil),
		(*Event_StreamStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preview_proto_rawDesc), len(file_preview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_preview_proto_goTypes,
		DependencyIndexes: file_preview_proto_depIdxs,
		MessageInfos:      file_preview_proto_msgTypes,
	}.Build()
	File_preview_proto = out.File
	file_preview_proto_goTypes = nil
	file_preview_proto_depIdxs = nil
}
